Update Homepage.html
mahbubul14/The-New-York-Times pull request #1
Opened 2021-03-22 15:24 UTC by mahbubul14

2021-03-24 17:56 UTC, teekaytech requested changes
### Status: Invalid Code Review Request :x: 

__Hi @mahbubul14, I commend you for the great effort put into this project. However, I have to mark the project as invalid due to the following reasons:__

- [ ] Your GitHub Actions checks are not running: to consider this project ready for review, you need to ensure that all GitHub Action Checks are running/passing successfully. 
- [ ] You should ensure that your PR has a descriptive title and summary. 
- [ ] You should also present a descriptive Readme for your project. [This template ](https://github.com/microverseinc/readme-template)might help.


Friendly reminder: You should make sure that your repo looks professional before review.
Please take a step back and read a lesson [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/).
Do not forget to apply 3 simple rules from this lesson (it will be easy as you can use a template provided there). This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!


* * *
**Please, do not open a new Pull Request for subsequent reviews. You should use the same Pull Request submitted for the first review unless it is requested otherwise.**

**Always post your inquiries and questions on this PR thread as a comment. You can mention me (@teekaytech) so I can see your comments and respond.**

* * * 

**_You can reach out to me on Twitter (@ola_lere), Github(@teekaytech), or slack (@taofeekolalere )_**

Happy Coding :man_technologist:

2021-03-26 14:38 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello @mahbubul14 :wave:

__You've really done well so far. Here're the major highlights of this PR:__

- PR title and summary is descriptive :ok_hand: 
- Readme has been improved :+1: 
- All linter checks running/passing successfully :100: 

__However, some changes are required before this project can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] There seems to be a bug with your deployment: your readme is being rendered instead of your webpage. This may be caused by your naming convention: you should name your webpage (the HTML file `Homepage.html`) to index.html. This will allow the GitHub page configuration to identify your homepage.
- [x] The `MIT license` link on your homepage seems to be broken. Kindly fix it.
- [x] Kindly work on the alignment of the items on your navbar: the Hamburger, Search, and the linked text should be aligned to the leftmost side, the NYT logo should be at the center, while the `Subscribe Now` and `Log In` buttons should be aligned to the rightmost side. 
**Original navbar**
![original](https://user-images.githubusercontent.com/26856491/112644603-e58c5900-8e45-11eb-90fb-3cc23a5fa28f.png)
**Cloned navbar**
![clone](https://user-images.githubusercontent.com/26856491/112645162-7e22d900-8e46-11eb-9928-bc4b4e39c0b7.png)

- [x]  The banner image should be wider than the remaining contents of the page.
**Original page**
![original](https://user-images.githubusercontent.com/26856491/112645358-add1e100-8e46-11eb-9234-8021271711ac.png)
**Cloned page**
![clone2](https://user-images.githubusercontent.com/26856491/112645195-8844d780-8e46-11eb-802f-8e5cdbf06af5.png)
- [ ] Your `Theory of Inflation` section is incomplete: you need to put the texts directly on top of the image, as we have on the original page. You should also observe the width of this section, as it's also wider than the other contents. Hint: You can use the `CSS grid` in this section.
**Original Page**
![original](https://user-images.githubusercontent.com/26856491/112645954-4ff1c900-8e47-11eb-9f5f-18938ff67bb0.png)
**Cloned Page**
![clone](https://user-images.githubusercontent.com/26856491/112645964-53855000-8e47-11eb-94d8-aa24b22568ea.png)
- [ ] Some of the `Suggested newsletters for you`, `Most Popular`, `More in Space and Astronomy` and `Editors' Picks` sections are not implemented while others are not well-aligned. Kindly ensure that these sections of your page look similar to what we have on the original page.
**Original Page**
![original](https://user-images.githubusercontent.com/26856491/112646482-d1e1f200-8e47-11eb-8cbe-d7330dca5a2e.png)
- [ ] Improvement is also required in your bottom navigation section.
- Ensure that the structure looks similar. Observe the difference in the images below and make necessary changes.
**Original**
![original](https://user-images.githubusercontent.com/26856491/112646793-238a7c80-8e48-11eb-89de-1fa268c26f85.png)
**Clone**
![clone](https://user-images.githubusercontent.com/26856491/112646839-300ed500-8e48-11eb-9685-c0727f17c880.png)
- All items in the bottom navigation section should be linked (i.e. use `<a>` tag around each of the items). Any valid value e.g. "#" is okay for each of their `href` attributes.
- [ ] The `Editor's Picks` section on the rightmost side is missing. Kindly implement it.
**Editor's Picks**
![original](https://user-images.githubusercontent.com/26856491/112647244-972c8980-8e48-11eb-8e3f-0f6a91c6b06a.png)



**[ OPTIONAL CHANGES ]**

- [ ] Use descriptive and meaningful class names as your CSS selectors. Check [this article](https://speckyboy.com/good-bad-css-practices) on common CSS bad practices and always avoid them.

* * *
**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review unless it is requested otherwise.**

**Always post your inquiries and questions on this PR thread as a comment. You can mention me (@teekaytech) so I can see your comments and respond.**

**REMINDER: As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 code reviews left for this project.**

_**Please make the required changes and submit another review request when you are done.**_

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2021-04-01 11:24 UTC, Berabjesus requested changes
# Status: REQUIRED CHANGES :warning: :construction: 
Hi @mahbubul14  An awesome start :+1: ! Very good README :100: Good job with the professional PR 👍 
### However, You have a few changes to carry out before we proceed so please take a look at the things you have to work on and their respective review comments below.

- [ ] Please make sure the NYT logo is a link.
- [x] The social media links are not correctly linked and styled.
- [x] Please use proper semantic HTML to avoid [Div soup](https://www.hackterms.com/div%20soup)
- [x] The project should be made with a combination of all three techniques ([float](https://css-tricks.com/all-about-floats/), [flex](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) and [grid](https://css-tricks.com/snippets/css/complete-guide-grid/)). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/flex_float_grid_requirement_pathwright.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/)). You have not used grid
- [x] Links in the footer are not properly tagged as anchor tags
- [ ]  CSS rules are repeated. For example `display: flex;` is used eleven times. Instead, create a common class for it and use it in the HTML
- [ ] No horizontal scrollbar. 

**Please have a look at the specific comments in the code below**

#### **Please, do not open a new Pull Request for subsequent reviews. You should use the same Pull Request submitted for the first review unless it is requested otherwise.**

#### ** ❗ You have two (2) remaining reviews. As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), when you reach the limit of 3 code reviews and your project was not approved, you will need to repeat the project. If you think that the code review was not fair, you can [request a second-opinion using this form.](https://airtable.com/shrmBIv6cXYrq4Fgv)**

#### **If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help** 
**HAPPY CODING :computer:[Bereket Beshane](https://bereketababu.me)** | [LinkedIn](https://linkedin.com/in/bereketbeshane) | [GitHub](https://github.com/Berabjesus)

2021-04-01 11:24 UTC, Berabjesus commented on index.html
> +        </div>
### main page 👇 
![m1](https://user-images.githubusercontent.com/64360974/113283356-dcd9ce00-92f0-11eb-93a4-e0b314d96e96.png)
### your page 👇 
![err1](https://user-images.githubusercontent.com/64360974/113283371-e2371880-92f0-11eb-8c45-b508b9a1f2cc.png)

**As you can see the deployed and the local version of your page is messed up on the social medial links section**

- [x] Please take a look at the code below and fix the image path for all the icons
```
// Bad Paths
<link rel="stylesheet" href="/assets/stylesheets/main.css">
<link rel="stylesheet" href="/assets/js/bootstrap.min.js">
<img src="/imgs/myimage.png">


// Good Paths
<link rel="stylesheet" href="./assets/stylesheets/main.css">
<link rel="stylesheet" href="./assets/js/bootstrap.min.js">
<img src="./imgs/myimage.png">
```

- [x] Make sure the images are links
- [x] Give the icons proper styling. They are currently overflowing to the right.

2021-04-01 11:24 UTC, Berabjesus commented on index.html
> +            <img src="/image/1st.jpg" alt="image" class="h1img">
- [x] Please take a look at the suggestion above and fix the image path for all the image.

2021-04-01 11:24 UTC, Berabjesus commented on index.html
> +            <h4>The Theory of Inflation</h4>
- [ ] Make sure 'The Theory of Inflation' section is centered horizontally. It is currently leaning to the left edge of the browser.

2021-04-01 11:24 UTC, Berabjesus commented on index.html
> +        <!-- suggested newletter section -->
### Main Page 👇 
![image](https://user-images.githubusercontent.com/64360974/113285833-14964500-92f4-11eb-9bb4-2885f9cfe7b5.png)

### Your page 👇 
![image](https://user-images.githubusercontent.com/64360974/113285892-27107e80-92f4-11eb-9165-6b30668642bd.png)

- [ ] Please use the suggestions above to fix the image paths for this section and all its image contents too
- [ ] Make sure this section is centered horizontally.

2021-04-01 11:24 UTC, Berabjesus commented on index.html
> +        </div>
### Main page 👇 
![image](https://user-images.githubusercontent.com/64360974/113285348-87eb8700-92f3-11eb-80a9-f26dcf6ed064.png)

### your page 👇 
![image](https://user-images.githubusercontent.com/64360974/113285398-9d60b100-92f3-11eb-8b3d-c0e5450b3d1d.png)

- [ ] Please work on the styling and the proper image path as specified above.

2021-04-01 11:52 UTC, mahbubul14 commented on index.html
> +        </div>
@berabjesus,
The icon absolutely looks good at my browser, Why it is so different from your side?

2021-04-01 13:00 UTC, Berabjesus commented on index.html
> +        </div>
Hi @mahbubul14, as you can see in the image below from a different browser, although the icons are sized properly, they don't load. The reason is properly explained above so please use the suggestion for the appropriate path to the SVGs.
![image](https://user-images.githubusercontent.com/64360974/113297308-1fa4a180-9303-11eb-8a67-a3ef12094253.png)

2021-04-02 00:10 UTC, Berabjesus requested changes
## Status: REQUIRED CHANGES :warning: :construction: 
#### Hi again @mahbubul14 ! You have done brilliantly to work on the requested changes 👍 👍 
#### However, you have missed just one mandatory change from the previous review. Please work on it and make a request for another code review. Have a look at the  OPTIONAL changes from the comments below too.

#### Mandatory
- [ ] Make sure the `suggested newsletter section` is centered and not stretched. Please have a look at the comments on the code below.

#### Optional
- [ ] When I first reviewed your project some of the stylings that were correct (Example: navbar Hamburger button was a link) are now incorrect. Please have a look at the comments on the code below and work on them.

### **Please, do not open a new Pull Request for subsequent reviews. You should use the same Pull Request submitted for the first review unless it is requested otherwise.**

### ** ❗ You have one (1) remaining review. As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), when you reach the limit of 3 code reviews and your project was not approved, you will need to repeat the project. If you think that the code review was not fair, you can [request a second-opinion using this form.](https://airtable.com/shrmBIv6cXYrq4Fgv)**

#### **If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help** 
**HAPPY CODING :computer:[Bereket Beshane](https://bereketababu.me)** | [LinkedIn](https://linkedin.com/in/bereketbeshane) | [GitHub](https://github.com/Berabjesus)

2021-04-02 00:10 UTC, Berabjesus commented on index.html
> +            <span class="nav-text">SPACE & COSMOS</span>
## Optional
- [ ] [OPTIONAL] When I first reviewed your project the highlighted sections were links and now the anchor tag is removed. Please make them a link again wrapping them in an anchor tag or using your previous implementation.

2021-04-02 00:10 UTC, Berabjesus commented on index.html
> +        <p id="p1" class="content"><b>SIGN UP FOR SCIENCE TIMES:</b> Get stories that capture the wonders of nature, the cosmos and the human body.<button class="sign-up" type="button">Sign Up</butto
## Optional: - When I first reviewed your project the sign up button was correct now it's not styled correctly please correct it.
original 👇 
![image](https://user-images.githubusercontent.com/64360974/113363954-00d1f980-935b-11eb-9418-9adf9595e6c4.png)

Yours 👇 
![image](https://user-images.githubusercontent.com/64360974/113363990-10514280-935b-11eb-844e-9fa8524fb21c.png)

2021-04-02 00:10 UTC, Berabjesus commented on index.html
> +        <h4 class="suggested-header">Suggested newsetter for you</h4>
## Mandatory

- [ ] As stated in the previous review, this section should be centered with the appropriate space. Currently, your page's layout is very much close to the edge of the browser.

#### main page 👇 
![image](https://user-images.githubusercontent.com/64360974/113365406-d97d2b80-935e-11eb-9908-44d08489c4cf.png)

#### yours 👇 
![image](https://user-images.githubusercontent.com/64360974/113365729-c28b0900-935f-11eb-873b-68f1808a9166.png)

## optional 

- [ ] Add the plus icons to the top right corner of the images here

2021-04-02 00:10 UTC, Berabjesus commented on index.html
> +        <img src="./image/logo.jpg" alt="image" class="footer-logo">
## Optional 

- [ ] The footer logo should also be a link.

2021-04-02 09:46 UTC, teekaytech approved these changes
# Status: Approved :green_circle: 

### Congratulations @mahbubul14  :tada: :clinking_glasses: 

_**Thank you for fixing the mandatory changes highlighted by the last reviewer :handshake:**_

**This project has passed all the mandatory requirements :clap: 
It is therefore approved :heavy_check_mark:**

**Comment(s)**
- In your best interest, you're advised to always strive to implement most (if not all) of the optional changes. These changes are there to make your project look professional.
- You might want to include instructions on how to set up your project in a development environment, on your Readme file. 

Again, congratulations, you can merge to the default branch.
Do not forget to fill the project completion form, as this is important for your weekly progress score.

**_Good luck with your next task._**

* * * 
**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2021-04-16 18:25 UTC, merged